---
- name: Verificar que los servicios existen
  ansible.windows.win_service_info:
    name: "{{ item.name }}"
  loop: "{{ services }}"
  register: service_info
  ignore_errors: yes  # Continuar incluso si falla

- name: Mostrar información de los servicios
  debug:
    var: service_info

- name: Detener los servicios (si existen)
  ansible.windows.win_service:
    name: "{{ item.item.name }}"
    state: stopped
  loop: "{{ service_info.results }}"
  when: item.exists
  register: stop_result
  until: stop_result is success  # Reintentar hasta que tenga éxito
  retries: "{{ max_retries }}"
  delay: "{{ delay_between_retries }}"
  ignore_errors: yes  # Continuar incluso si falla

- name: Mostrar resultado de la detención de los servicios
  debug:
    var: stop_result

- name: Esperar {{ wait_time }} segundos después de detener todos los servicios
  ansible.windows.win_shell: |
    Start-Sleep -Seconds {{ wait_time }}
